# -*- mode: ruby -*-
cask_args appdir: '/Applications'

tap 'homebrew/services'

brew 'atuin'
brew 'bat'
brew 'bottom'
brew 'difftastic'
brew 'direnv'
brew 'dust'
brew 'eza'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'herdr'
brew 'jq'
brew 'lazygit'
brew 'libvterm'
brew 'ripgrep'
brew 'starship'
brew 'tealdeer'
brew 'tree-sitter'
brew 'wget'
brew 'zoxide'
brew 'zsh'
brew 'zsh-completions'
brew 'zstd'

brew 'neovim'

cask '1password-cli'
cask 'claude-code@latest'
cask 'codex'
cask 'orbstack'
cask 'superhuman'
cask 'font-inconsolata'
cask 'font-inconsolata-nerd-font'
cask 'obsidian'
