#!/usr/bin/env sh

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

/usr/local/bin/brew tap Homebrew/bundle
/usr/local/bin/brew install mas

/usr/local/bin/brew bundle

mkdir -p ~/Projects

[ -d ~/Projects/emacs.d ] || (git clone git@github.com:bradwright/emacs.d ~/Projects/emacs.d && cd ~/Projects/emacs.d && make && cd -)

make

# Set default shell to ZSH
if grep -qL /usr/local/bin/zsh /etc/shells; then
	echo "/usr/local/bin/zsh" >> /etc/shells
fi
chsh -s /usr/local/bin/zsh
