#!/usr/bin/env sh

[ -d /usr/local/Homebrew ] || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

/usr/local/bin/brew tap Homebrew/bundle
[ `which mas` ] || /usr/local/bin/brew install mas

/usr/local/bin/brew bundle

mkdir -p ~/Projects

[ -d ~/Projects/emacs.d ] || (git clone git@github.com:bradwright/emacs.d ~/Projects/emacs.d && cd ~/Projects/emacs.d && make && cd -)

make

if [ "$SHELL" != "/usr/local/bin/zsh" ]; then
    # Set default shell to ZSH
    if grep -qL /usr/local/bin/zsh /etc/shells; then
	    sudo echo "/usr/local/bin/zsh" >> /etc/shells
    fi
    chsh -s /usr/local/bin/zsh
fi

# Go packages
go get -u golang.org/x/tools/cmd/godoc \
    && go get -u github.com/nsf/gocode \
    && go get -u github.com/rogpeppe/godef \
    && go get -u github.com/kisielk/errcheck \
    && pkill -f gocode || true

# Local overrides
cat <<EOF > ~/.local_zshrc
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
cdpath=($HOME/Projects ~)
EOF
