#!/usr/bin/env sh

[ -f `which apm` ] || exit 1

apm install advanced-open-file
apm install atom-fuzzy-grep
apm insyall atom-typescript
apm install editorconfig
apm install git-plus
apm install go-debug
apm install go-plus
apm install highlight-line
apm install language-docker
apm install language-r
apm install linter
apm install markdown-scroll-sync
apm install markdown-writer
